export const GET_RANDOM_DOG = "GET_RANDOM_DOG";
export const GET_RANDOM_DOG_SUCCESS = "GET_RANDOM_DOG_SUCCESS";
export const GET_RANDOM_DOG_FAILURE = "GET_RANDOM_DOG_FAILURE";

export const GET_BY_BREED = "GET_BY_BREED";
export const GET_BY_BREED_SUCCESS = "GET_BY_BREED_SUCCESS";
export const GET_BY_BREED_FAILURE = "GET_BY_BREED_FAILURE";

export const GET_BREED_LIST = "GET_BREED_LIST";
export const GET_BREED_LIST_SUCCESS = "GET_BREED_LIST_SUCCESS";
export const GET_BREED_LIST_FAILURE = "GET_BREED_LIST_FAILURE";
